yolo_model:

  config_file:
    name: yolo.2.0.cfg
  weight_file:
    name: yolo.2.0.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - wrong
      - class
      - names
      - boat4
      - bottle
      - bus15
      - car
      - cat6
      - chair5
      - cow
      - dining table4
      - dog
      - horse
      - motorbike1
      - person
      - potted plant
      - sheep
      - sofa
      - train
      - tv monitor
      - aeroplane
      - bicycle
      - bird
      - boat1
      - bottle2
      - bus
      - car
      - cat
      - chair
      - cow
      - dining table
      - dog
      - horse
      - motorbike
      - person
      - potted plant
      - sheep
      - sofa
      - train
      - tv monitor
      - aeroplane
      - bicycle
      - bird
      - boat
      - bottle
      - bus
      - car
      - cat
      - chair
      - cow
      - dining table
      - dog
      - horse
      - motorbike
      - person
      - potted plant
      - sheep
      - sofa
      - train
      - tv monitor
      - aeroplane
      - bicycle
      - bird
      - boat
      - bottle
      - bus
      - car
      - cat
      - chair
      - cow
      - dining table
      - dog
      - horse
      - motorbike
      - person
      - potted plant
      - sheep
      - sofa
      - train
      - tv monitor